### ISSUE TITLE
JSON-Body not encoded according to spec

### ISSUE THREAD

**Issue by gtudan** [pak3nuh/dart_pact_consumer#4]
If I add a json body, it will be included "as is" to the PACT.

```json
"body": {
    "deviceId": "4de4adb9-21ee-47e3-aeb4-8cf8ed6c109a"
  }
```

But the Spec defines a wrapper-object for the body (with fields content/content-type/encoding):

https://github.com/pact-foundation/pact-specification/tree/version-4#synchronoushttp

```json
"body": {
      "contentType": "application/json",
      "encoded": false,
      "content": [
        {
          "size": 1445211,
          "name": "testId254",
          "id": 32432
        }
      ]
    },
```

**Comment by pak3nuh** [comment]
Yeah its not up to V4 spec, it was most likely taken from V3 references as it receives the body inline.
The main issue is that this was tested with the agnostic pact verifier with a pact broker in between and it worked. Maybe those tools aren't ready for V4 as well.
I'll need to think about this because I'm not sure if I want to support V4 or V3 at this point.

**Comment by gtudan** [comment]
I wouldn't mind going for V3 as V4 is still WIP and most of the PACT-Tools have bugs when used with v4. I had to patch the Junit5-Verifier to get it to work (https://github.com/pact-foundation/pact-jvm/pull/1369).  Just my 2cents...

**Comment by pak3nuh** [comment]
Hi @gtudan 
I think we are better of downgrading to version 3 until the spec and all tooling are stable.
I've pushed that should be compliant with version 3, can you check it out?
https://github.com/pak3nuh/dart_pact_consumer/tree/fix/downgrade-pact-version

**Comment by gtudan** [comment]
Looks good to me 👍
